grammar ValidVersion ;
range: RANGE ;
RANGE: (LEFT_PARENS | LEFT_BRACKET) VERSION? COMMA VERSION? (RIGHT_BRACKET | RIGHT_PARENS) EOF ;

VERSION: VERSION_ELEMENT (DOT VERSION_ELEMENT (DOT VERSION_ELEMENT)? )? ;

VERSION_ELEMENT: ZERO | NON_ZERO (NUMBER)*  ;
NON_ZERO: '1'..'9' ;
ZERO: '0' ;
NUMBER: ZERO | NON_ZERO ;


LEFT_BRACKET: '[' ;
RIGHT_BRACKET: ']' ;
LEFT_PARENS: '(' ;
RIGHT_PARENS: ')' ;

DOT: '.' ;
COMMA: ',' ;

WS                 : [\t ]+ -> skip ;

